// Code generated by gkit. DO NOT EDIT.
package delivery

import (
	"gateway/application/routing/delivery/handler"
	"gateway/application/routing/delivery/handler/custom"
	"gateway/application/routing/delivery/handler/user"
	"gateway/package/settings"
)

type routingConfig struct {
	handler                 handler.RequestHandler
	remoteServiceName       string
	remoteServiceMethod     string
	remoteServicePermission string
}
