// Code generated by gkit. DO NOT EDIT.
package delivery

import (
	"gateway/application/routing/delivery/handler"
	"gateway/application/routing/delivery/handler/user"
	"gateway/package/settings"
)

type routingConfig struct {
	handler                 handler.RequestHandler
	remoteServiceName       string
	remoteServiceMethod     string
	remoteServicePermission string
}

func buildRegistry(cfg *settings.Config) map[string]routingConfig {
	return map[string]routingConfig{
		"POST:/api/v1/user-service/login": {
			user.NewLoginHandler(cfg),
			"UserService",
			"Login",
			"",
		},
		"GET:/api/v1/user-service/profile": {
			user.NewGetProfileHandler(cfg),
			"UserService",
			"GetProfile",
			"",
		},
		"POST:/api/v1/user-service/user": {
			user.NewCreateUserHandler(cfg),
			"UserService",
			"CreateUser",
			"",
		},
	}
}
