// Code generated by gkit. DO NOT EDIT.
package delivery

import (
	"github.com/gin-gonic/gin"
)

func (h *RoutingHandler) RegisterAPIUserService(routes *gin.RouterGroup) {
	routes.POST("/login", h.handle())
	routes.GET("/profile", h.handle())
}
