// Code generated by gkit. DO NOT EDIT.
package user

import(
    
    
    

    "gateway/proto/user"
    "gateway/package/settings"

    "gateway/package/wrapper"
    "gateway/package/monitor"
    "go.elastic.co/apm/v2"
)

type getProfileHandler struct {
}

func NewGetProfileHandler(cfg *settings.Config) *getProfileHandler {
    return &getProfileHandler{}
}

// @Summary permission: 
// @Tags UserService
// @Produce json
// @Success 200 {object} user.user.GetProfileResponse
// @Router /api/v1/invoice/profile [get]
func (handler *getProfileHandler) Handle(ctx *wrapper.Context) (interface{}, error) {
    monitor.SetApmContext(apm.DetachedContext(ctx.Request.Context()))
    data := &user.user.GetProfileRequest{}


    return data, nil
}
