// Code generated by gkit. DO NOT EDIT.
package user

import (
    

    "gateway/package/settings"
    "gateway/proto/user"
    
    "gateway/package/wrapper"
    "gateway/package/monitor"
    "go.elastic.co/apm/v2"
    
)

type loginHandler struct {
}

func NewLoginHandler(cfg *settings.Config) *loginHandler {
    return &loginHandler{}
}

// @Summary permission: 
// @Tags UserService
// @Accept json
// @Produce json
// @Param username  body  string false "<param_description>"
// @Param password  body  string false "<param_description>"
// @Param body  body  user.user.LoginRequest true "Body example"
// @Success 200 {object} user.user.LoginResponse
// @Router /api/v1/invoice/login [post]
func (handler *loginHandler) Handle(ctx *wrapper.Context) (interface{}, error) {
    monitor.SetApmContext(apm.DetachedContext(ctx.Request.Context()))
    data := user.user.LoginRequest{}
    if err := ctx.BindJSON(&data); err != nil {
        return nil, err
    }

    return &data, nil
}
