// Code generated by gkit. DO NOT EDIT.
package grpc

import (
	"fmt"

	"google.golang.org/grpc/metadata"

	"gateway/package/settings"
	"gateway/proto/user"

	"gateway/package/grpc"
	"gateway/package/monitor"
	//"context"
)

func (client *userServiceClient) initMethodRegistry() {
	client.methodRegistry = map[string]func(interface{}, map[string]string) (interface{}, error){
		"Login":      client.login,
		"GetProfile": client.getProfile,
	}
}

type userServiceClient struct {
	grpcClient     user.UserServiceClient
	methodRegistry map[string]func(interface{}, map[string]string) (interface{}, error)
}

func NewUserServiceClient(config *settings.Config) *userServiceClient {
	// using WithInsecure() because no SSL running
	cc, err := grpc.CreateGRPCClientConn(config.Service.UserServiceUrl, false)
	if err != nil {
		fmt.Println("Could not connect:", err)
	}

	client := userServiceClient{
		grpcClient: user.NewUserServiceClient(cc),
	}
	client.initMethodRegistry()

	return &client
}

func (client *userServiceClient) GetMethodRegistry() map[string]func(interface{}, map[string]string) (interface{}, error) {
	return client.methodRegistry
}

func (client *userServiceClient) login(data interface{}, md map[string]string) (interface{}, error) {
	ctx := monitor.GetApmContext()
	//ctx := context.Background()
	for k, v := range md {
		ctx = metadata.AppendToOutgoingContext(ctx, k, v)
	}
	return client.grpcClient.Login(ctx, data.(*user.LoginRequest))
}

func (client *userServiceClient) getProfile(data interface{}, md map[string]string) (interface{}, error) {
	ctx := monitor.GetApmContext()
	//ctx := context.Background()
	for k, v := range md {
		ctx = metadata.AppendToOutgoingContext(ctx, k, v)
	}
	return client.grpcClient.GetProfile(ctx, data.(*user.GetProfileRequest))
}
