// Code generated by gkit. DO NOT EDIT.
package service

import(
    "gateway/package/settings"
    "gateway/application/routing/delivery/remote"
    "gateway/application/routing/delivery/remote/grpc"
)

func initRemoteServiceClientRegistry(config *settings.Config) map[string]RemoteServiceClient {
    return map[string]RemoteServiceClient {
        "UserService": remote.NewGrpcServiceClient(grpc.NewUserServiceClient(config)),
    }
}
