// Code generated by gkit. DO NOT EDIT.
package application

func (s *Server) initUserRouting() {
	h := s.handler
	router := s.router.Group("")

	rUserUser := router.Group("/api/v1/user-service")
	rUserUser.Use(h.Authorization())
	h.RegisterAPIUserService(rUserUser)
}
