// Code generated by gkit. DO NOT EDIT.
package application

func (s *Server) initPublicRouting() {
	h := s.handler
	router := s.router.Group("")

	pR := router.Group("/api/v1/")
	h.RegisterPublicAPI(pR)
}

func (s *Server) initPrivateRouting() {
	h := s.handler
	router := s.router.Group("")

	pR := router.Group("/api/v1/")
	pR.Use(h.Authorization())
	h.RegisterPrivateAPI(pR)
}

func (s *Server) initUserRouting() {
	h := s.handler
	router := s.router.Group("")

	rUserUser := router.Group("/api/v1/user-service")
	rUserUser.Use(h.Authorization())
	h.RegisterAPIUserService(rUserUser)
}
